export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const GET_ALL_RECEPIES = "GET_ALL_RECEPIES";
export const GET_FREEZER_PANTRY = "GET_FREEZER_PANTRY";
export const GET_FRIDGE_PANTRY = "GET_FRIDGE_PANTRY";
export const GET_STORAGE_PANTRY = "GET_STORAGE_PANTRY";
export const GET_OTHER_PANTRY = "GET_OTHER_PANTRY";
export const NUMBER_OF_DOCS = "NUMBER_OF_DOCS";

export const FIRST_STEP = "FIRST_STEP";
export const SECOND_STEP = "SECOND_STEP";
export const THIRD_STEP = "THIRD_STEP";
export const FOURTH_STEP = "FOURTH_STEP";
